server:
 port: 8765

spring:
  application:
    name: zuul-cloud-gateway
  

  cloud:
   gateway:
      routes:
      - id: user-service
        uri: http://localhost:9002/users/
        predicates:
        - Path=/users/**
        
      - id: department-service
        uri: http://localhost:9001/departments/ 
        predicates:
         - Path=/departments/**
         
      - id: users-service
        uri: http://localhost:9001
        predicates:
        - Path=/api/user/**
        
      - id: transactions-service
        uri: http://localhost:9002
        predicates:
        - Path=/api/transaction/**
        
      - id: team2-backend
        uri: http://team2-backend-container-1:9010
        predicates:
        - Path=/products/**

eureka:
  client:
    service-url:
     defaultZone: http://eurekha-server-container:8761/eureka
    fetch-registry: true
    register-with-eureka: true
      